name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://orgf3615da0.crm11.dynamics.com/'
        user-name: 'd365admin@finopsfuntimes.onmicrosoft.com'
        password-secret: ${{ secrets.PACKAGINGSECRET }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://orgf3615da0.crm11.dynamics.com/'
        user-name: 'd365admin@finopsfuntimes.onmicrosoft.com'
        password-secret: ${{ secrets.PACKAGINGSECRET }}
        solution-name: MyProjectOpsExtentions
        solution-output-file: out/exported/MyProjectOpsExtentions.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/MyProjectOpsExtentions.zip
        solution-folder: out/solutions/MyProjectOpsExtentions
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/MyProjectOpsExtentions
        solution-target-folder: CE_solution/MyProjectOpsExtentions
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
